[project]
name = "openmyid"
version = "0.1.0"
description = "Access myID (https://myid.gov.au) without a smartphone"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "meatie>=0.1.23",
    "pydantic>=2.11.5",
    "pyjwt>=2.10.1",
]
